dependencies:
  config:
    - field.storage.node.field_event_geolocation
    - field.storage.group.field_group_geolocation
    - field.storage.profile.field_profile_geolocation
field_settings:
  node_lat_cos:
    label: 'Geolocation » Latitude cosine'
    datasource_id: 'entity:node'
    property_path: 'field_event_geolocation:lat_cos'
    type: decimal
    dependencies:
      config:
        - field.storage.node.field_event_geolocation
  node_lat_sin:
    label: 'Geolocation » Latitude sine'
    datasource_id: 'entity:node'
    property_path: 'field_event_geolocation:lat_sin'
    type: decimal
    dependencies:
      config:
        - field.storage.node.field_event_geolocation
  node_lng_rad:
    label: 'Geolocation » Longitude radian'
    datasource_id: 'entity:node'
    property_path: 'field_event_geolocation:lng_rad'
    type: decimal
    dependencies:
      config:
        - field.storage.node.field_event_geolocation
  group_type:
    label: 'Group type'
    datasource_id: 'entity:group'
    property_path: type
    type: string
  group_lat_cos:
    label: 'Geolocation » Latitude cosine'
    datasource_id: 'entity:group'
    property_path: 'field_group_geolocation:lat_cos'
    type: decimal
    dependencies:
      config:
        - field.storage.group.field_group_geolocation
  group_lat_sin:
    label: 'Geolocation » Latitude sine'
    datasource_id: 'entity:group'
    property_path: 'field_group_geolocation:lat_sin'
    type: decimal
    dependencies:
      config:
        - field.storage.group.field_group_geolocation
  group_lng_rad:
    label: 'Geolocation » Longitude radian'
    datasource_id: 'entity:group'
    property_path: 'field_group_geolocation:lng_rad'
    type: decimal
    dependencies:
      config:
        - field.storage.group.field_group_geolocation
  profile_lat_cos:
    label: 'Geolocation » Latitude cosine'
    datasource_id: 'entity:profile'
    property_path: 'field_profile_geolocation:lat_cos'
    type: decimal
    dependencies:
      config:
        - field.storage.profile.field_profile_geolocation
  profile_lat_sin:
    label: 'Geolocation » Latitude sine'
    datasource_id: 'entity:profile'
    property_path: 'field_profile_geolocation:lat_sin'
    type: decimal
    dependencies:
      config:
        - field.storage.profile.field_profile_geolocation
  profile_lng_rad:
    label: 'Geolocation » Longitude radian'
    datasource_id: 'entity:profile'
    property_path: 'field_profile_geolocation:lng_rad'
    type: decimal
    dependencies:
      config:
        - field.storage.profile.field_profile_geolocation