dependencies:
  config:
    - field.storage.profile.field_profile_geolocation
field_settings:
  profile_lat_cos:
    label: 'Geolocation » Latitude cosine'
    datasource_id: 'entity:profile'
    property_path: 'field_profile_geolocation:lat_cos'
    type: decimal
    dependencies:
      config:
        - field.storage.profile.field_profile_geolocation
  profile_lat_sin:
    label: 'Geolocation » Latitude sine'
    datasource_id: 'entity:profile'
    property_path: 'field_profile_geolocation:lat_sin'
    type: decimal
    dependencies:
      config:
        - field.storage.profile.field_profile_geolocation
  profile_lng_rad:
    label: 'Geolocation » Longitude radian'
    datasource_id: 'entity:profile'
    property_path: 'field_profile_geolocation:lng_rad'
    type: decimal
    dependencies:
      config:
        - field.storage.profile.field_profile_geolocation