dependencies:
  config:
    - field.storage.group.field_group_geolocation
field_settings:
  group_lat_cos:
    label: 'Geolocation » Latitude cosine'
    datasource_id: 'entity:group'
    property_path: 'field_group_geolocation:lat_cos'
    type: decimal
    dependencies:
      config:
        - field.storage.group.field_group_geolocation
  group_lat_sin:
    label: 'Geolocation » Latitude sine'
    datasource_id: 'entity:group'
    property_path: 'field_group_geolocation:lat_sin'
    type: decimal
    dependencies:
      config:
        - field.storage.group.field_group_geolocation
  group_lng_rad:
    label: 'Geolocation » Longitude radian'
    datasource_id: 'entity:group'
    property_path: 'field_group_geolocation:lng_rad'
    type: decimal
    dependencies:
      config:
        - field.storage.group.field_group_geolocation