display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button: true
      filters:
        label:
          id: label
          table: search_api_index_social_groups
          field: label
          relationship: none
          group_type: group
          admin_label: ''
          operator: '='
          value:
            min: ''
            max: ''
            value: ''
          group: 1
          exposed: true
          expose:
            operator_id: label_op
            label: Title
            description: ''
            use_operator: false
            operator: label_op
            identifier: label
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              administrator: '0'
              contentmanager: '0'
              sitemanager: '0'
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin_id: search_api_string
      header:
        area:
          content:
            value: '<h4 class="section-title">Group results</h4><p>If you are searching for users, <a href="/search/users/">click here</a> If you are searching for content, <a href="/search/content/">click here</a></p>'
  page:
    display_options:
      exposed_block: true
  page_no_value:
    display_options:
      exposed_block: true
      header:
        area:
          content:
            value: '<h4 class="section-title">Group results</h4><p>If you are searching for users, <a href="/search/users/">click here</a> If you are searching for content, <a href="/search/content/">click here</a></p>'
