display:
  default:
    display_options:
      header:
        area:
          content:
            value: '<h4 class="section-title">Content results</h4><p>If you are searching for users, <a href="/search/users">click here</a> If you are searching for groups, <a href="/search/groups">click here</a></p>'
  page:
    display_options:
      header:
        area:
          content:
            value: '<h4 class="section-title">Content results</h4><p>If you are searching for users, <a href="/search/users">click here</a> If you are searching for groups, <a href="/search/groups">click here</a></p>'
