display:
  default:
    display_options:
      header:
        area:
          content:
            value: '<h4 class="section-title">Member results</h4><p>If you are searching for content, <a href="/search/content">click here</a> If you are searching for groups, <a href="/search/groups">click here</a></p>'
  page_no_value:
    display_options:
      header:
        area:
          content:
            value: '<h4 class="section-title">Member results</h4><p>If you are searching for content, <a href="/search/content">click here</a> If you are searching for groups, <a href="/search/groups">click here</a></p>'
